# Generated by Django 3.2.7 on 2021-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante_actividad',
            name='entregaFile',
            field=models.FileField(blank=True, null=True, upload_to='entregas/'),
        ),
    ]
