# Generated by Django 3.2.8 on 2021-11-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='estudiante_actividad',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.actividad'),
        ),
        migrations.AddField(
            model_name='estudiante_actividad',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='estructura_de_datos',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='seed.estructuradedatos'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='estudianteAct',
            field=models.ManyToManyField(through='seed.Estudiante_Actividad', to='usuarios.Estudiante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tema_actividad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seed.tema'),
        ),
    ]
