# Generated by Django 3.2.8 on 2021-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='estudiantes',
            field=models.FileField(blank=True, null=True, upload_to='estudiantes/'),
        ),
    ]
