# Generated by Django 3.2.8 on 2021-11-03 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiate_actividad',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
