# Generated by Django 3.2.8 on 2021-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0002_estudiate_actividad_fecha_entrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={},
        ),
        migrations.AddField(
            model_name='docente',
            name='es_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='es_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='url_img',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
