# Generated by Django 3.2.8 on 2021-11-30 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0002_alter_grupo_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='temas',
            field=models.ForeignKey(blank=True, default='0000', null=True, on_delete=django.db.models.deletion.CASCADE, to='seed.tema'),
        ),
    ]
