# Generated by Django 3.2.8 on 2021-11-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0003_alter_grupo_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='temas',
        ),
    ]
