# Generated by Django 3.2.8 on 2021-11-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0003_auto_20211103_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seed.grupo'),
        ),
    ]
