# Generated by Django 3.2.8 on 2021-11-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0004_estudiante_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='estado',
            field=models.CharField(choices=[('AC', 'ACTIVO'), ('IN', 'INACTIVO'), ('AR', 'ARCHIVADO')], default='AC', max_length=9),
        ),
        migrations.AlterField(
            model_name='tema',
            name='grupo_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.grupo'),
        ),
    ]
