# Generated by Django 3.2.8 on 2021-10-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0004_auto_20211021_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='grupo',
        ),
    ]
