# Generated by Django 3.2.8 on 2021-10-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0005_remove_estudiante_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
