# Generated by Django 3.2.8 on 2021-10-21 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0006_delete_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='docente',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
