# Generated by Django 3.2.8 on 2021-10-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0008_docente_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
