# Generated by Django 3.2.8 on 2021-10-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0009_alter_docente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estdiante',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
