# Generated by Django 3.2.8 on 2021-10-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0010_estdiante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estdiante',
            new_name='Estudiante',
        ),
    ]
