# Generated by Django 3.2.8 on 2021-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0011_rename_estdiante_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='id',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='codigo_grupo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
