# Generated by Django 3.2.8 on 2021-10-21 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0012_auto_20211021_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grupo_xd',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='seed.grupo'),
        ),
    ]
