# Generated by Django 3.2.8 on 2021-10-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0015_alter_estudiante_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre_estudiante',
            field=models.CharField(default='', max_length=50),
        ),
    ]
