# Generated by Django 3.2.8 on 2021-10-21 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0016_estudiante_nombre_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='seed.grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='codigo_grupo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
