# Generated by Django 3.2.8 on 2021-10-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0018_alter_estudiante_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=350)),
            ],
        ),
    ]
