# Generated by Django 3.2.8 on 2021-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0019_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='estudiante_actividad',
            field=models.ManyToManyField(to='seed.Estudiante'),
        ),
    ]
