# Generated by Django 3.2.8 on 2021-10-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0020_actividad_estudiante_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('grupo_tema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seed.actividad')),
            ],
        ),
    ]
