# Generated by Django 3.2.8 on 2021-10-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0021_tema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='nombre',
            new_name='nombre_ac',
        ),
        migrations.RenameField(
            model_name='tema',
            old_name='codigo',
            new_name='codigo_tema',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tema_actividad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seed.tema'),
        ),
        migrations.AddField(
            model_name='tema',
            name='nombre_tema',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tema',
            name='grupo_tema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seed.grupo'),
        ),
        migrations.CreateModel(
            name='EstructuraDeDatos',
            fields=[
                ('codigo_ed', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ed', models.CharField(max_length=50)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seed.actividad')),
            ],
        ),
    ]
