# Generated by Django 3.2.8 on 2021-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0022_auto_20211023_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
