# Generated by Django 3.2.7 on 2021-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0023_alter_grupo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='url_img',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='url_img',
            field=models.CharField(default='', max_length=250),
        ),
    ]
