# Generated by Django 3.2.7 on 2021-10-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0025_grupo_url_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='codigo',
        ),
    ]
